# Generated by Django 2.0 on 2017-12-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_name', models.CharField(max_length=200)),
                ('create_date', models.DateField(verbose_name='date publiched')),
                ('is_check', models.BooleanField(default=False)),
            ],
        ),
    ]
