# Generated by Django 2.0 on 2017-12-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20171220_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todo_name',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
