# Generated by Django 2.0 on 2017-12-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20171220_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todo_name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
